title: Pranjal Singh
#logo: /assets/img/headshot_circle.png
description: Creative and driven individual with hands-on project experience in data storytelling and insight generation. Passionate about uncovering patterns and applying data-driven solutions to real-world problems.

#show_downloads: true
theme: jekyll-theme-minimal
